'use strict';
/**
 * server/src/lib/academicPrograms.js
 *
 * Loads academic program and minor data from:
 *   server/data/academic-programs.json
 *   server/data/academic-minors.json
 *
 * Data files are generated by:
 *   node server/scripts/build-academic-programs.mjs
 *
 * Never live-scrapes on request.
 */

const path = require('path');
const fs = require('fs');

const PROGRAMS_PATH = path.join(__dirname, '../../data/academic-programs.json');
const MINORS_PATH   = path.join(__dirname, '../../data/academic-minors.json');

let programsCache = null;
let minorsCache   = null;

// ---------------------------------------------------------------------------
// Load helpers
// ---------------------------------------------------------------------------

/**
 * IDs that start with these prefixes are Qatar-campus or cross-listed duplicates
 * that would otherwise appear twice in the picker with identical display labels.
 *
 * Qatar campus: Texas A&M at Qatar offers Chemical, Electrical, Mechanical, and
 * Petroleum Engineering under paths like "catalog-major:qatar/...". The catalog
 * scraper includes them because the path contains "engineering", giving them the
 * same college label as the College Station counterpart.
 *
 * Cross-listed Computer Engineering: the program appears under both
 * "engineering/computer-science/" and "engineering/electrical-computer/" in the
 * TAMU catalog; only the ECE-department entry should be shown.
 */
const DUPLICATE_ID_PREFIXES = [
  'catalog-major:qatar/',
  'catalog-major:engineering/computer-science/computer-engineering',
];

function isDuplicateProgram(p) {
  return DUPLICATE_ID_PREFIXES.some((prefix) => p.id.startsWith(prefix));
}

function loadPrograms() {
  if (programsCache) return programsCache;
  const raw = fs.readFileSync(PROGRAMS_PATH, 'utf8');
  const parsed = JSON.parse(raw);
  const all = Array.isArray(parsed.programs) ? parsed.programs : [];
  programsCache = all.filter((p) => !isDuplicateProgram(p));
  return programsCache;
}

function loadMinors() {
  if (minorsCache) return minorsCache;
  try {
    const raw = fs.readFileSync(MINORS_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    minorsCache = Array.isArray(parsed.minors) ? parsed.minors : [];
  } catch {
    minorsCache = [];
  }
  return minorsCache;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * List academic programs (majors + minors combined, or filtered by type).
 *
 * @param {{ type?: 'major'|'minor', q?: string, catalog?: string }} opts
 * @returns {Array}
 */
function listAcademicPrograms({ type, q, catalog } = {}) {
  const programs = type === 'minor' ? [] : loadPrograms().slice();
  const minors   = type === 'major' ? [] : loadMinors().slice();
  let combined   = [...programs, ...minors];

  if (catalog) {
    combined = combined.filter((p) => p.catalog === catalog);
  }

  if (q) {
    const lc = q.toLowerCase();
    combined = combined.filter(
      (p) =>
        p.title.toLowerCase().includes(lc) ||
        (p.college ?? '').toLowerCase().includes(lc) ||
        (p.department ?? '').toLowerCase().includes(lc)
    );
  }

  return combined.sort((a, b) => a.title.localeCompare(b.title));
}

/**
 * List only major programs.
 * @param {{ q?: string, catalog?: string }} opts
 */
function listMajors(opts = {}) {
  return listAcademicPrograms({ ...opts, type: 'major' });
}

/**
 * List only minor programs.
 * @param {{ q?: string, catalog?: string }} opts
 */
function listMinors(opts = {}) {
  return listAcademicPrograms({ ...opts, type: 'minor' });
}

/**
 * Get a single academic program by id.
 * Throws with statusCode 404 if not found.
 * @param {string} id
 */
function getAcademicProgram(id) {
  const all = [...loadPrograms(), ...loadMinors()];
  const found = all.find((p) => p.id === id);
  if (!found) {
    const err = new Error(`Academic program not found: ${id}`);
    err.statusCode = 404;
    throw err;
  }
  return found;
}

/**
 * Validate an array of program IDs.
 * Returns { valid: Array, invalid: Array<string> }.
 *
 * @param {string[]} ids
 * @param {'major'|'minor'|undefined} type  optional type constraint
 */
function validateProgramIds(ids, type) {
  if (!Array.isArray(ids)) return { valid: [], invalid: [] };
  const all = type === 'minor' ? loadMinors()
             : type === 'major' ? loadPrograms()
             : [...loadPrograms(), ...loadMinors()];
  const map = new Map(all.map((p) => [p.id, p]));
  const valid = [];
  const invalid = [];
  for (const id of ids) {
    if (map.has(id)) {
      valid.push(map.get(id));
    } else {
      invalid.push(id);
    }
  }
  return { valid, invalid };
}

/** True when the same program id appears more than once. */
function hasDuplicateIds(ids) {
  const list = (ids ?? []).filter(Boolean);
  return new Set(list).size !== list.length;
}

/** Most minors a student may be enrolled in at once. */
const MAX_MINORS = 2;

/** Majors beyond the primary one. Still gated on secondaryProgramEnabled. */
const MAX_ADDITIONAL_MAJORS = 1;

module.exports = {
  listAcademicPrograms, listMajors, listMinors, getAcademicProgram, validateProgramIds,
  hasDuplicateIds, MAX_MINORS, MAX_ADDITIONAL_MAJORS,
};
